### PR TITLE
Adds nightly pytest marker

### PR DESCRIPTION
**Pull request by bmbouter**
[noissue]

### CODE REVIEW

**Review by fao89 — APPROVED** [review]
This LGTM, but I have a pytest question,

when running pytest not nightly, wouldn't it run parallel tests?
or not parallel would run nightly tests?

**Comment by bmbouter** [comment]
> This LGTM, but I have a pytest question,
> 
> when running pytest not nightly, wouldn't it run parallel tests? or not parallel would run nightly tests?

I've been asking myself similar questions. Here's my current thinking at least. The nightly test run will run "all tests" like it does now. All non-nightly test runs will disinclude the nightly tagged tests by specifying `-m "not nightly"`. I'm putting this into a plugin_template PR right now actually, I'd like to know what you think is best.

**Comment by bmbouter** [comment]
@fao89 wdyt about https://github.com/pulp/plugin_template/pull/567

**Comment by fao89** [comment]
> > This LGTM, but I have a pytest question,
> > when running pytest not nightly, wouldn't it run parallel tests? or not parallel would run nightly tests?
> 
> I've been asking myself similar questions. Here's my current thinking at least. The nightly test run will run "all tests" like it does now. All non-nightly test runs will disinclude the nightly tagged tests by specifying `-m "not nightly"`. I'm putting this into a plugin_template PR right now actually, I'd like to know what you think is best.

I don't have an opinion on that, I'm just afraid of collision of pytest markers, I believe `-m "not nightly"`will trigger parallel tests, but I'm not sure if this will happen

**Pull request merged**
